/**
 * Hand-written clue bank for the Sports Crossword. Every clue is a fact that does not go stale (no current
 * rosters or "reigning champion" clues). Answers are letters only, 3 to 9 long, and appear once.
 */
export interface Entry { word: string; clue: string }

export const CROSSWORD_BANK: Entry[] = [
  // Baseball
  { word: 'HOMER', clue: 'Four-bagger' },
  { word: 'BUNT', clue: 'Squeeze play tactic' },
  { word: 'INNING', clue: 'One of nine in a regulation baseball game' },
  { word: 'DUGOUT', clue: 'Where the bench players sit, below field level' },
  { word: 'BULLPEN', clue: 'Where relievers warm up' },
  { word: 'ERA', clue: 'Pitching stat: earned runs per nine innings, briefly' },
  { word: 'RBI', clue: 'Batting stat for driving a run home, briefly' },
  { word: 'UMP', clue: 'Calls balls and strikes, for short' },
  { word: 'MOUND', clue: 'Raised spot for the pitcher' },
  { word: 'GLOVE', clue: 'A fielder wears one' },
  { word: 'WALKOFF', clue: 'Hit that ends the game in the home team\'s last at-bat' },
  { word: 'SHORTSTOP', clue: 'Infielder between second and third' },
  { word: 'CATCHER', clue: 'Player who wears the tools of ignorance' },
  { word: 'STEAL', clue: 'Take a base without a hit' },
  { word: 'SLIDER', clue: 'Breaking pitch that moves sideways' },
  { word: 'CURVE', clue: 'Twelve-to-six pitch, informally' },
  { word: 'FASTBALL', clue: 'A heater' },
  { word: 'GRANDSLAM', clue: 'Home run with the bases loaded' },
  { word: 'TRIPLE', clue: 'Three-base hit' },
  { word: 'OUTFIELD', clue: 'Left, center and right, together' },
  { word: 'PENNANT', clue: 'League championship banner in baseball' },
  { word: 'RUTH', clue: 'The Bambino' },
  { word: 'AARON', clue: 'Hammerin\' Hank' },
  { word: 'JETER', clue: 'Derek with five rings as a Yankee' },
  { word: 'OHTANI', clue: 'Two-way star Shohei' },
  { word: 'CUBS', clue: 'Wrigley Field team' },
  { word: 'METS', clue: 'Queens baseball team' },
  { word: 'REDS', clue: 'Cincinnati nine' },
  { word: 'ASTROS', clue: 'Houston baseball team' },
  { word: 'TWINS', clue: 'Minnesota baseball team' },
  { word: 'ORIOLES', clue: 'Baltimore birds' },
  { word: 'PADRES', clue: 'San Diego baseball team' },
  { word: 'MARINERS', clue: 'Seattle baseball team' },
  // Football
  { word: 'PUNT', clue: 'Fourth-down kick, often' },
  { word: 'SACK', clue: 'Quarterback takedown behind the line' },
  { word: 'BLITZ', clue: 'Extra rushers sent after the quarterback' },
  { word: 'HUDDLE', clue: 'Pre-play gathering' },
  { word: 'SNAP', clue: 'Center-to-quarterback handoff that starts a play' },
  { word: 'FUMBLE', clue: 'Lose the ball while carrying it' },
  { word: 'ENDZONE', clue: 'Where touchdowns are scored' },
  { word: 'GRIDIRON', clue: 'Football field, informally' },
  { word: 'YARD', clue: 'Football field unit' },
  { word: 'SAFETY', clue: 'Two-point score for the defense' },
  { word: 'TACKLE', clue: 'Bring down the ball carrier' },
  { word: 'HELMET', clue: 'Football headgear' },
  { word: 'KICKOFF', clue: 'Play that starts each half' },
  { word: 'AUDIBLE', clue: 'Play changed at the line of scrimmage' },
  { word: 'REDZONE', clue: 'Inside the opponent\'s 20-yard line' },
  { word: 'ONSIDE', clue: 'Kind of short kick a trailing team tries' },
  { word: 'SUPERBOWL', clue: 'NFL title game' },
  { word: 'LOMBARDI', clue: 'Trophy named for a Packers coach' },
  { word: 'BRADY', clue: 'Seven-time Super Bowl champion Tom' },
  { word: 'MONTANA', clue: '49ers great Joe' },
  { word: 'PAYTON', clue: 'Sweetness, of the Bears' },
  { word: 'RICE', clue: 'Jerry with the most career receiving yards' },
  { word: 'BEARS', clue: 'Chicago NFL team' },
  { word: 'JETS', clue: 'Gang Green of the NFL' },
  { word: 'RAMS', clue: 'Los Angeles NFL team that played in St. Louis' },
  { word: 'COLTS', clue: 'Indianapolis NFL team' },
  { word: 'CHIEFS', clue: 'Kansas City NFL team' },
  { word: 'RAIDERS', clue: 'Silver and Black of the NFL' },
  { word: 'BENGALS', clue: 'Cincinnati NFL team' },
  { word: 'BROWNS', clue: 'Cleveland NFL team' },
  { word: 'LIONS', clue: 'Detroit NFL team' },
  { word: 'SAINTS', clue: 'New Orleans NFL team' },
  { word: 'PACKERS', clue: 'Green Bay NFL team' },
  { word: 'STEELERS', clue: 'Pittsburgh NFL team' },
  { word: 'TITANS', clue: 'Tennessee NFL team' },
  { word: 'TEXANS', clue: 'Houston NFL team' },
  { word: 'VIKINGS', clue: 'Minnesota NFL team' },
  { word: 'FALCONS', clue: 'Atlanta NFL team' },
  // Basketball
  { word: 'DUNK', clue: 'Slam, on the court' },
  { word: 'LAYUP', clue: 'Close shot off the backboard' },
  { word: 'REBOUND', clue: 'Grab a missed shot' },
  { word: 'ASSIST', clue: 'Pass that leads to a basket' },
  { word: 'SWISH', clue: 'Nothing but net' },
  { word: 'HOOP', clue: 'Basket\'s rim' },
  { word: 'TRAVEL', clue: 'Too many steps without a dribble' },
  { word: 'FOUL', clue: 'It may send a shooter to the line' },
  { word: 'DRIBBLE', clue: 'Bounce the ball while moving' },
  { word: 'TIPOFF', clue: 'Opening jump ball' },
  { word: 'BACKCOURT', clue: 'The two guards, together' },
  { word: 'PAINT', clue: 'Lane near the basket' },
  { word: 'THREE', clue: 'Shot from beyond the arc' },
  { word: 'BUZZER', clue: 'Sound at the end of a quarter' },
  { word: 'KOBE', clue: 'Black Mamba' },
  { word: 'LEBRON', clue: 'King James' },
  { word: 'JORDAN', clue: 'Six-time Finals MVP Michael' },
  { word: 'SHAQ', clue: 'Big Diesel, briefly' },
  { word: 'BIRD', clue: 'Larry Legend' },
  { word: 'MAGIC', clue: 'Orlando NBA team, or Lakers great Johnson' },
  { word: 'NETS', clue: 'Brooklyn NBA team' },
  { word: 'HEAT', clue: 'Miami NBA team' },
  { word: 'JAZZ', clue: 'Utah NBA team' },
  { word: 'SUNS', clue: 'Phoenix NBA team' },
  { word: 'LAKERS', clue: 'Showtime team of the 1980s' },
  { word: 'CELTICS', clue: 'Boston NBA team' },
  { word: 'KNICKS', clue: 'Madison Square Garden NBA team' },
  { word: 'BULLS', clue: 'Chicago NBA team' },
  { word: 'SPURS', clue: 'San Antonio NBA team' },
  { word: 'WARRIORS', clue: 'Golden State NBA team' },
  { word: 'PISTONS', clue: 'Bad Boys of Detroit' },
  // Hockey
  { word: 'PUCK', clue: 'Hockey disc' },
  { word: 'RINK', clue: 'Hockey surface' },
  { word: 'ICING', clue: 'Hockey violation for shooting the puck the length of the ice' },
  { word: 'GOALIE', clue: 'Net minder' },
  { word: 'SLAPSHOT', clue: 'Hardest hockey shot, with a big windup' },
  { word: 'ZAMBONI', clue: 'Ice resurfacer' },
  { word: 'STANLEY', clue: 'Lord whose name is on hockey\'s Cup' },
  { word: 'HATTRICK', clue: 'Three goals in one game' },
  { word: 'GRETZKY', clue: 'The Great One' },
  { word: 'ORR', clue: 'Bruins defenseman Bobby' },
  { word: 'BRUINS', clue: 'Boston NHL team' },
  { word: 'OILERS', clue: 'Edmonton NHL team' },
  { word: 'FLAMES', clue: 'Calgary NHL team' },
  { word: 'DUCKS', clue: 'Anaheim NHL team' },
  { word: 'SHARKS', clue: 'San Jose NHL team' },
  { word: 'RANGERS', clue: 'Broadway Blueshirts' },
  { word: 'PENALTY', clue: 'Time in the box' },
  // Soccer
  { word: 'GOAL', clue: 'Score in soccer' },
  { word: 'HEADER', clue: 'Shot off the forehead' },
  { word: 'KEEPER', clue: 'Only player allowed to use hands' },
  { word: 'PITCH', clue: 'Soccer field, in Britain' },
  { word: 'STRIKER', clue: 'Main goal scorer up front' },
  { word: 'DERBY', clue: 'Match between local rivals' },
  { word: 'OFFSIDE', clue: 'Flag for being behind the last defender too early' },
  { word: 'CORNER', clue: 'Kick from the flag' },
  { word: 'NUTMEG', clue: 'Pass the ball through a defender\'s legs' },
  { word: 'PELE', clue: 'Brazilian with three World Cup wins' },
  { word: 'MESSI', clue: 'Argentina\'s captain at the 2022 World Cup' },
  { word: 'RONALDO', clue: 'CR7' },
  { word: 'MARADONA', clue: 'Hand of God scorer' },
  { word: 'ARSENAL', clue: 'The Gunners' },
  { word: 'CHELSEA', clue: 'The Blues of west London' },
  { word: 'REALMADRID', clue: 'Los Blancos' },
  // Tennis and golf
  { word: 'ACE', clue: 'Serve that is never touched' },
  { word: 'LOVE', clue: 'Zero, in tennis' },
  { word: 'DEUCE', clue: 'Forty-all' },
  { word: 'VOLLEY', clue: 'Hit before the bounce' },
  { word: 'RACKET', clue: 'Tennis gear with strings' },
  { word: 'SERVE', clue: 'Point starter in tennis' },
  { word: 'LOB', clue: 'High shot over the net player' },
  { word: 'BAGEL', clue: 'Six-love set, slangily' },
  { word: 'SERENA', clue: 'Twenty-three-time major winner Williams' },
  { word: 'NADAL', clue: 'Rafa, king of clay' },
  { word: 'FEDERER', clue: 'Roger with eight Wimbledon titles' },
  { word: 'TEE', clue: 'Golf peg' },
  { word: 'PAR', clue: 'Expected score on a golf hole' },
  { word: 'EAGLE', clue: 'Two under on a hole' },
  { word: 'BIRDIE', clue: 'One under on a hole' },
  { word: 'BOGEY', clue: 'One over on a hole' },
  { word: 'PUTT', clue: 'Shot on the green' },
  { word: 'CADDIE', clue: 'Bag carrier on the course' },
  { word: 'WEDGE', clue: 'Lofted golf club' },
  { word: 'FAIRWAY', clue: 'Mowed path from tee to green' },
  { word: 'BUNKER', clue: 'Sand trap' },
  { word: 'MULLIGAN', clue: 'Do-over off the tee, in casual golf' },
  { word: 'TIGER', clue: 'Golfer Woods' },
  { word: 'MASTERS', clue: 'Augusta tournament with a green jacket' },
  // Everything else
  { word: 'BOLT', clue: 'Usain, fastest man ever over 100 meters' },
  { word: 'PHELPS', clue: 'Michael with 23 Olympic golds' },
  { word: 'ALI', clue: 'The Greatest, in boxing' },
  { word: 'JAB', clue: 'Quick straight punch' },
  { word: 'UPPERCUT', clue: 'Rising punch to the chin' },
  { word: 'KNOCKOUT', clue: 'Fight-ending blow' },
  { word: 'BOUT', clue: 'Boxing match' },
  { word: 'TKO', clue: 'Ref-stopped finish, briefly' },
  { word: 'RELAY', clue: 'Race with a baton' },
  { word: 'HURDLE', clue: 'Track obstacle' },
  { word: 'SPRINT', clue: 'All-out dash' },
  { word: 'MARATHON', clue: 'A 26.2-mile race' },
  { word: 'LAP', clue: 'Once around the track' },
  { word: 'PODIUM', clue: 'Where the top three stand' },
  { word: 'MEDAL', clue: 'Gold, silver or bronze' },
  { word: 'TORCH', clue: 'Olympic flame carrier' },
  { word: 'SLALOM', clue: 'Ski race through gates' },
  { word: 'LUGE', clue: 'Feet-first sled event' },
  { word: 'CURLING', clue: 'Sport with stones and brooms' },
  { word: 'OAR', clue: 'Rowing tool' },
  { word: 'REGATTA', clue: 'Boat race event' },
  { word: 'PITSTOP', clue: 'Quick tire change during a race' },
  { word: 'NASCAR', clue: 'Daytona 500 sanctioning body' },
  { word: 'POLE', clue: 'Front-row starting spot' },
  { word: 'DRAFT', clue: 'Annual pick of new players' },
  { word: 'ROOKIE', clue: 'First-year player' },
  { word: 'COACH', clue: 'One calling the plays from the sideline' },
  { word: 'REF', clue: 'Whistle blower, for short' },
  { word: 'MASCOT', clue: 'Costumed team cheerleader' },
  { word: 'SWEEP', clue: 'Win every game of a series' },
  { word: 'DYNASTY', clue: 'Team that wins title after title' },
  { word: 'TROPHY', clue: 'Champion\'s hardware' },
  { word: 'OVERTIME', clue: 'Extra period after a tie' },
  { word: 'UNDERDOG', clue: 'Team not expected to win' },
  { word: 'UPSET', clue: 'Underdog\'s win' },
  { word: 'ESPN', clue: 'Network behind SportsCenter' },
  { word: 'MVP', clue: 'Top individual award, briefly' },
  { word: 'NBA', clue: 'Hoops league, briefly' },
  { word: 'NFL', clue: 'Football league, briefly' },
  { word: 'NHL', clue: 'Hockey league, briefly' },
  { word: 'MLB', clue: 'Baseball league, briefly' },
  { word: 'GOAT', clue: 'Greatest of all time, briefly' },
  { word: 'ARENA', clue: 'Indoor venue' },
  { word: 'STADIUM', clue: 'Big outdoor venue' },
  { word: 'TAILGATE', clue: 'Parking lot party before a game' },
  { word: 'JERSEY', clue: 'Numbered team shirt' },
  { word: 'WHISTLE', clue: 'It stops play' },
  { word: 'SCOREBOARD', clue: 'It shows the score' },
];
