import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE } from '@/lib/site';
import { ContactLink, contactVerb } from '@/components/ContactLink';
import { LegalPage } from '../_components/LegalPage';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: `${SITE.name} is an independent fan project, not affiliated with EA, the NFL, the NFLPA, or any team. Entertainment only, no gambling.`,
  alternates: { canonical: '/legal/disclaimer' },
};

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      summary={
        <ul>
          <li>We are an independent fan project. Not EA, not the NFL, not the players&apos; union, not any team.</li>
          <li>We use player ratings as facts, the way a newspaper prints a box score. We do not copy EA&apos;s screens, art, or branding.</li>
          <li>Player photos are used to identify players. Ask us to remove one and it is gone within 48 hours.</li>
          <li>Every simulated season is fiction. No betting, no real money, no prizes, no odds.</li>
        </ul>
      }
    >
      <h2>No affiliation</h2>
      <p>
        {SITE.name} is an independent project. It is not affiliated with, endorsed by, sponsored by, or approved by Electronic Arts Inc., EA SPORTS, the
        National Football League, NFL Properties, NFL Enterprises, the NFL Players Association, or any NFL team, player, or coach. No one at any of those
        organizations has reviewed or approved this site.
      </p>

      <h2>Trademarks</h2>
      <p>
        EA, EA SPORTS, and Madden NFL are trademarks of Electronic Arts Inc. NFL, the NFL shield, team names, nicknames, logos, and uniform designs are
        trademarks of the NFL and its member clubs. NFLPA and related marks belong to the NFL Players Association. All other marks belong to their
        respective owners. We use names only to describe what we are talking about (for example, &quot;EA Sports Madden NFL ratings&quot; or a team&apos;s
        name next to its roster). That kind of descriptive, nominative use does not mean any owner endorses us, and we do not use these marks as our own
        branding.
      </p>

      <h2>Ratings are facts, used descriptively</h2>
      <p>
        Player ratings are numbers: a quarterback&apos;s throw power is 94, a corner&apos;s speed is 92. We reference those numbers as factual data about how
        players are rated, and we credit the source every time.
      </p>
      <p>
        In <em>Feist Publications, Inc. v. Rural Telephone Service Co.</em> (1991), the U.S. Supreme Court held that facts cannot be copyrighted, even if
        someone worked hard to gather them. In that case, a phone company could not stop a competitor from using the names and numbers in its phone book,
        because names and numbers are facts. What copyright protects is original creative expression: the way facts are selected, arranged, or
        presented, if that is creative. In plain terms: the number is not ownable, but a particular creative presentation of it can be.
      </p>
      <p>
        So we use the numbers and build our own presentation. Our page layouts, charts, game engine, formulas, and writing are ours. We think this is a fair
        reading of the law, but we are not your lawyer, and nothing here is legal advice.
      </p>

      <h2>We do not reproduce EA&apos;s interface or branding</h2>
      <p>
        We do not copy EA&apos;s screens, menus, player cards, fonts, logos, artwork, or audio. We do not use the Madden name as part of our brand. We do
        not distribute any game files.
      </p>

      <h2>Player images</h2>
      <p>
        Player headshots come from public sports media and are shown at small sizes solely to identify the player being discussed. We believe this is fair
        use. Rights belong to their owners. If you own an image and want it removed, {contactVerb('dmca')} <ContactLink kind="dmca" />. We remove images within 48 hours of a
        request, no argument required. Formal copyright notices can also follow our <Link href="/legal/dmca">DMCA Policy</Link>. Every player page falls back
        to a plain monogram when no image is shown.
      </p>

      <h2>Simulations are fictional</h2>
      <p>
        Game results, simulated seasons, records, and &quot;17-0&quot; outcomes are generated by our own engine using ratings and randomness. They are fiction.
        They are not predictions, projections, or statements about real players, teams, or games, and they do not reflect anyone&apos;s actual ability.
      </p>

      <h2>No gambling. Entertainment only.</h2>
      <ul>
        <li>No real-money entry. Every game is free.</li>
        <li>No prizes for game results or leaderboard position.</li>
        <li>No odds, lines, spreads, or picks against the number.</li>
        <li>No links to sportsbooks, and no sportsbook advertising we control.</li>
      </ul>
      <p>
        {SITE.name} is for entertainment. If gambling is a problem for you or someone you know, call or text 1-800-GAMBLER (U.S.).
      </p>

      <h2>No warranty</h2>
      <p>
        Data may be out of date or wrong. We sync ratings on a schedule and show when data may be stale, but we make no guarantee of accuracy. See our{' '}
        <Link href="/legal/terms">Terms</Link> for the full warranty disclaimer.
      </p>

      <h2>Contact</h2>
      <p><ContactLink kind="legal" />. By mail: {SITE.mailingAddress}.</p>
    </LegalPage>
  );
}
